version: '3.9'
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=asses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123news
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/newsapp
    ports:
      - 8000:8000
    depends_on:
      - db